var graphgraphmy = {
	nodes:[
		{nodeName:"Alignment 3", group:1},
		{nodeName:"Alignment 11", group:1},
		{nodeName:"Alignment 12", group:1},
		{nodeName:"Alignment 5", group:1},
		{nodeName:"Alignment 7", group:1},
		{nodeName:"Alignment 4", group:1},
		{nodeName:"Alignment 8", group:1},
		{nodeName:"Alignment 10", group:1},
		{nodeName:"Alignment 1", group:1},
		{nodeName:"Alignment 6", group:1},
		{nodeName:"Alignment 9", group:1},
		{nodeName:"Alignment 0", group:1},
		{nodeName:"Alignment2", group:1}
	],
	links:[
		{source:11 , target:10 , value:2},
		{source:10 , target:8 , value:2},
		{source:10 , target:12 , value:1},
		{source:10 , target:0 , value:1},
		{source:10 , target:3 , value:1},
		{source:4 , target:10 , value:1},
		{source:6 , target:10 , value:5},
		{source:10 , target:1 , value:1},
		{source:10 , target:2 , value:1},
		{source:11 , target:8 , value:3},
		{source:11 , target:12 , value:1},
		{source:11 , target:0 , value:3},
		{source:11 , target:3 , value:3},
		{source:11 , target:4 , value:1},
		{source:11 , target:6 , value:1},
		{source:11 , target:1 , value:1},
		{source:11 , target:2 , value:1},
		{source:11 , target:8 , value:3},
		{source:11 , target:0 , value:3},
		{source:11 , target:3 , value:3},
		{source:11 , target:9 , value:3},
		{source:11 , target:8 , value:3},
		{source:11 , target:0 , value:3},
		{source:11 , target:3 , value:3},
		{source:11 , target:9 , value:3},
		{source:11 , target:10 , value:2},
		{source:10 , target:8 , value:2},
		{source:5 , target:10 , value:1},
		{source:11 , target:5 , value:2},
		{source:5 , target:8 , value:2},
		{source:5 , target:12 , value:1},
		{source:5 , target:0 , value:1},
		{source:5 , target:3 , value:1},
		{source:4 , target:5 , value:1},
		{source:5 , target:6 , value:1},
		{source:5 , target:1 , value:1},
		{source:5 , target:2 , value:1},
		{source:11 , target:5 , value:2},
		{source:5 , target:8 , value:2},
		{source:11 , target:7 , value:1},
		{source:7 , target:8 , value:1},
		{source:7 , target:0 , value:1},
		{source:7 , target:3 , value:1},
		{source:9 , target:7 , value:2},
		{source:11 , target:9 , value:3},
		{source:9 , target:8 , value:1},
		{source:9 , target:5 , value:2},
		{source:9 , target:5 , value:2},
		{source:9 , target:3 , value:1},
		{source:9 , target:7 , value:2},
		{source:4 , target:9 , value:4},
		{source:4 , target:9 , value:4},
		{source:4 , target:9 , value:4},
		{source:4 , target:9 , value:4},
		{source:6 , target:10 , value:5},
		{source:10 , target:7 , value:4},
		{source:6 , target:10 , value:5},
		{source:6 , target:10 , value:5},
		{source:10 , target:7 , value:4},
		{source:6 , target:7 , value:1},
		{source:10 , target:7 , value:4},
		{source:6 , target:10 , value:5},
		{source:10 , target:7 , value:4},
		{source:7 , target:1 , value:3},
		{source:7 , target:2 , value:3},
		{source:7 , target:1 , value:3},
		{source:7 , target:2 , value:3},
		{source:7 , target:1 , value:3},
		{source:7 , target:2 , value:3}
	]
}
